DROP DATABASE IF EXISTS tastingroomservice;
DROP USER IF EXISTS `tasting_room`@`%`;
CREATE DATABASE IF NOT EXISTS tastingroomservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `tasting_room`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `tastingroomservice`.* TO `tasting_room`@`%`;
FLUSH PRIVILEGES;